main: main.cpp
	g++ $^ -o $@ -L/home/mozat/ssd/caffe/build/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu -L/usr/local/cuda-8.0/lib64 -lcaffe -lcudart -lcublas -lcurand -lprotobuf -lboost_system -lboost_filesystem -I/home/mozat/ssd/caffe/include -I/usr/local/cuda-8.0/include/
