main: main.cpp
	g++ $^ -o $@ -I/usr/include/ -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_filesystem

main2: main2.cpp
	g++ $^ -o $@ -I/usr/include/ -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_filesystem
